import { useEffect, useState } from 'react'
import { Spin } from 'antd'
import { sheetsApi } from '../api/client'
import { ActionSheet } from '../store'

/**
 * PrintView — Renders a pixel-perfect HTML replica of the PDF generated by PdfService.java.
 * This is the LIVE PREVIEW of how the PDF will look when generated.
 * Layout matches: A4 (595×842pt), margins 40pt, same fonts, grid, response lines, etc.
 */

const GRID_HEADERS = ['', 'G.M.', 'D. GM', "EX. M's", 'ACC.', 'PM / PE', 'M.C.', 'L.A.', 'O.M.', 'E/M', 'PL. E', 'Others', '']
const GRID_COL_WIDTHS = [80, 32, 32, 32, 32, 42, 32, 32, 32, 32, 32, 40, 50]

const API_BASE = import.meta.env.VITE_API_URL || ''

export default function PrintView() {
  const [sheets, setSheets] = useState<ActionSheet[]>([])
  const [loading, setLoading] = useState(true)
  const [pdfBlobUrl, setPdfBlobUrl] = useState<string | null>(null)
  const [isPrintMode, setIsPrintMode] = useState(false)

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const idsString = params.get('ids')
    const mode = params.get('mode')
    const printMode = mode === 'print'
    setIsPrintMode(printMode)

    if (!idsString) {
      setLoading(false)
      return
    }

    const ids = idsString.split(',').map(id => id.trim())

    const fetchAll = async () => {
      try {
        const results = await Promise.all(
          ids.map(id => sheetsApi.getById(id).then(res => res.data))
        )
        const validSheets = results.filter(Boolean)
        setSheets(validSheets)

        // Print mode: fetch the actual generated PDF (includes attachments)
        if (printMode && validSheets.length > 0) {
          const sheetsWithPdf = validSheets.filter((s: ActionSheet) => s.pdfPath)
          if (sheetsWithPdf.length > 0) {
            try {
              const pdfPath = sheetsWithPdf[0].pdfPath!
              const pdfUrl = `${API_BASE}/api/projects/serve-file?path=${encodeURIComponent(pdfPath)}`
              const response = await fetch(pdfUrl, {
                method: 'GET',
                headers: {
                  'ngrok-skip-browser-warning': 'true',
                  'Accept': 'application/pdf',
                },
              })
              if (response.ok) {
                const blob = await response.blob()
                setPdfBlobUrl(URL.createObjectURL(blob))
              }
            } catch (pdfErr) {
              console.error('Failed to fetch PDF for printing:', pdfErr)
            }
          }
        }
      } catch (err) {
        console.error('Failed to fetch some sheets for printing', err)
      } finally {
        setLoading(false)
      }
    }

    fetchAll()

    return () => {
      if (pdfBlobUrl) URL.revokeObjectURL(pdfBlobUrl)
    }
  }, [])

  if (loading) {
    return <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <Spin size="large" tip="Preparing documents for printing..." />
    </div>
  }

  if (sheets.length === 0) {
    return <div style={{ padding: 40, fontFamily: 'sans-serif' }}>No sheets selected or found for printing.</div>
  }

  // ═══ PRINT MODE: Show the actual generated PDF (includes attachments) ═══
  if (isPrintMode && pdfBlobUrl) {
    return (
      <>
        <style>{`
          html, body { margin: 0; padding: 0; height: 100%; overflow: hidden; }
        `}</style>
        <iframe
          id="pdf-print-frame"
          src={pdfBlobUrl}
          style={{
            width: '100vw',
            height: '100vh',
            border: 'none',
            display: 'block',
          }}
          title="PDF Print"
          onLoad={() => {
            // Auto-trigger print dialog once PDF is loaded in iframe
            setTimeout(() => {
              const iframe = document.getElementById('pdf-print-frame') as HTMLIFrameElement
              if (iframe?.contentWindow) {
                try {
                  iframe.contentWindow.print()
                } catch {
                  window.print()
                }
              }
            }, 500)
          }}
        />
      </>
    )
  }

  // ═══ PREVIEW MODE: Pixel-perfect HTML replica of the PDF ═══
  return (
    <div style={{ background: 'white', minHeight: '100vh', paddingBottom: 20 }}>
      <style>{`
        @media print {
          body { background: white !important; margin: 0; padding: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .page-break { page-break-after: always; }
          .page-break:last-child { page-break-after: auto; }
          .a4-page { box-shadow: none !important; margin: 0 !important; }
        }
        @media screen {
          .a4-page { box-shadow: 0 2px 12px rgba(0,0,0,0.3); margin: 20px auto; }
        }
        .a4-page {
          width: 595px;
          height: 842px;
          background: white;
          position: relative;
          overflow: hidden;
          font-family: 'SansSerif', 'Segoe UI', Arial, sans-serif;
          color: black;
        }
        .a4-page * { box-sizing: border-box; }
      `}</style>

      {sheets.map((sheet) => {
        const fd = sheet.formData || {}
        return (
          <div key={sheet.id} className="page-break">
            <div className="a4-page">
              {/* ── 1. HEADER ── */}
              <div style={{
                position: 'absolute', top: 38, left: 40,
                fontStyle: 'italic', fontSize: 9, fontFamily: "'SansSerif', Arial, sans-serif",
              }}>
                AL-AHLIA CONTRACTING GROUP (W.L.L.)
              </div>
              <div style={{
                position: 'absolute', top: 38, right: 40,
                fontWeight: 700, fontSize: 11, fontFamily: "'Dialog', 'Traditional Arabic', 'Segoe UI', serif",
                direction: 'rtl',
              }}>
                المجموعة الأهلية للمقاولات
              </div>

              {/* Center Logo */}
              <div style={{
                position: 'absolute',
                top: 30,
                left: '50%',
                transform: 'translateX(-50%)',
                width: 65,
                height: 45,
                border: '0.5px solid black',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                overflow: 'hidden',
              }}>
                <img src="/acg_logo.jpg" alt="ACG" style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                  onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; (e.target as HTMLImageElement).parentElement!.innerHTML = '<span style="font-size:10px;font-weight:bold">ACG</span>' }}
                />
              </div>

              {/* ── 2. TITLE BOX ── */}
              <div style={{
                position: 'absolute',
                top: 90,
                left: '50%',
                transform: 'translateX(-50%)',
                width: 140,
                height: 20,
                border: '1px solid black',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 'bold',
                fontStyle: 'italic',
                fontSize: 14,
              }}>
                ACTION SHEET
              </div>

              {/* ── 3. DOCUMENT TYPE GRID ── */}
              <div style={{
                position: 'absolute',
                top: 125,
                left: 140,
                display: 'flex',
                height: 18,
              }}>
                {[
                  { label: 'LETTER', w: 50 }, { check: 'isLetter', w: 20 },
                  { label: 'FAX', w: 35 }, { check: 'isFax', w: 20 },
                  { label: 'COPY', w: 35 }, { check: 'isCopy', w: 20 },
                  { label: 'E.MAIL', w: 45 }, { check: 'isEmail', w: 20 },
                ].map((col, i) => (
                  <div key={i} style={{
                    width: col.w,
                    height: 18,
                    border: '1px solid black',
                    borderLeft: i === 0 ? '1px solid black' : 'none',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: 9,
                    fontWeight: 'bold',
                  }}>
                    {col.label ? col.label : (
                      fd[col.check!] ? <span style={{ fontSize: 12, fontWeight: 'bold' }}>✓</span> : ''
                    )}
                  </div>
                ))}
              </div>

              {/* ── 4. INFO ROWS ── */}
              {/* ROW 1: Original To | Date Received */}
              <div style={{
                position: 'absolute', top: 160, left: 40, width: 515, height: 25,
                border: '1px solid black', display: 'flex',
              }}>
                {/* Left: Original To */}
                <div style={{ width: 280, height: '100%', display: 'flex', alignItems: 'center', borderRight: '1px solid black' }}>
                  <span style={{ fontSize: 10, paddingLeft: 5, width: 80 }}>Original To</span>
                  <span style={{ fontSize: 10, fontWeight: 'bold' }}>{fd.originalTo || ''}</span>
                </div>
                {/* Arabic: الاصل إلى */}
                <div style={{ position: 'absolute', left: 200, top: 5, fontSize: 11, fontWeight: 700, fontFamily: "'Dialog', 'Traditional Arabic', serif", direction: 'rtl' }}>
                  الاصل إلى :
                </div>
                {/* Right: Date Received */}
                <div style={{ flex: 1, height: '100%', display: 'flex', alignItems: 'center' }}>
                  <span style={{ fontSize: 10, paddingLeft: 5 }}>Date Received :</span>
                  <span style={{ fontSize: 10, fontWeight: 'bold', marginLeft: 5 }}>{fd.dateReceived || ''}</span>
                </div>
                {/* Arabic: تاريخ الاستلام */}
                <div style={{ position: 'absolute', right: 5, top: 5, fontSize: 11, fontWeight: 700, fontFamily: "'Dialog', 'Traditional Arabic', serif", direction: 'rtl' }}>
                  تاريخ الاستلام :
                </div>
              </div>

              {/* ROW 2: Ref No | Document Date */}
              <div style={{
                position: 'absolute', top: 185, left: 40, width: 515, height: 25,
                border: '1px solid black', borderTop: 'none', display: 'flex',
              }}>
                <div style={{ width: 280, height: '100%', display: 'flex', alignItems: 'center', borderRight: '1px solid black' }}>
                  <span style={{ fontSize: 10, paddingLeft: 5, width: 80 }}>Ref. No.</span>
                  <span style={{ fontSize: 10, fontWeight: 'bold' }}>{fd.refNo || ''}</span>
                </div>
                <div style={{ position: 'absolute', left: 200, top: 5, fontSize: 11, fontWeight: 700, fontFamily: "'Dialog', 'Traditional Arabic', serif", direction: 'rtl' }}>
                  رقم الكتاب :
                </div>
                <div style={{ flex: 1, height: '100%', display: 'flex', alignItems: 'center' }}>
                  <span style={{ fontSize: 10, paddingLeft: 5 }}>Document Date :</span>
                  <span style={{ fontSize: 10, fontWeight: 'bold', marginLeft: 5 }}>{fd.documentDate || ''}</span>
                </div>
                <div style={{ position: 'absolute', right: 5, top: 5, fontSize: 11, fontWeight: 700, fontFamily: "'Dialog', 'Traditional Arabic', serif", direction: 'rtl' }}>
                  تاريخ الكتاب :
                </div>
              </div>

              {/* ROW 3: From (Full Width) */}
              <div style={{
                position: 'absolute', top: 210, left: 40, width: 515, height: 25,
                border: '1px solid black', borderTop: 'none', display: 'flex', alignItems: 'center',
              }}>
                <span style={{ fontSize: 10, paddingLeft: 5, width: 80 }}>From</span>
                <span style={{ fontSize: 10, paddingLeft: 0 }}>:</span>
                <span style={{ fontSize: 10, fontWeight: 'bold', marginLeft: 10 }}>{fd.from || ''}</span>
                <div style={{ position: 'absolute', right: 20, top: 5, fontSize: 11, fontWeight: 700, fontFamily: "'Dialog', 'Traditional Arabic', serif", direction: 'rtl' }}>
                  من :
                </div>
              </div>

              {/* ROW 4: Subject (80px height) */}
              <div style={{
                position: 'absolute', top: 235, left: 40, width: 515, height: 80,
                border: '1px solid black', borderTop: 'none',
              }}>
                <span style={{ fontSize: 10, position: 'absolute', left: 5, top: 6 }}>Subject</span>
                <span style={{ fontSize: 10, position: 'absolute', left: 80, top: 6 }}>:</span>
                {/* Underlines — positioned at y+22, y+47, y+72 to give text room above */}
                <div style={{ position: 'absolute', left: 80, top: 22, right: 40, borderBottom: '1px solid black' }} />
                <div style={{ position: 'absolute', left: 80, top: 47, right: 40, borderBottom: '1px solid black' }} />
                <div style={{ position: 'absolute', left: 80, top: 72, right: 40, borderBottom: '1px solid black' }} />
                {/* Subject text — each line of text sits above its underline */}
                <div style={{
                  position: 'absolute', left: 90, top: 6, right: 45,
                  fontSize: 10, fontWeight: 'bold', lineHeight: '25px',
                  overflow: 'hidden', maxHeight: 72,
                  wordBreak: 'break-word',
                }}>
                  {fd.subject || sheet.title || ''}
                </div>
                <div style={{ position: 'absolute', right: 5, top: 6, fontSize: 11, fontWeight: 700, fontFamily: "'Dialog', 'Traditional Arabic', serif", direction: 'rtl' }}>
                  الموضوع :
                </div>
              </div>

              {/* ── 5. DISTRIBUTION GRID ── */}
              {(() => {
                const gridTop = 325
                const gridRowH = 22
                const gridLeft = 40
                // Calculate column x positions
                const colPositions: number[] = []
                let cx = 0
                for (let i = 0; i < GRID_COL_WIDTHS.length; i++) {
                  colPositions.push(cx)
                  cx += GRID_COL_WIDTHS[i]
                }
                const totalW = cx

                return (
                  <div style={{
                    position: 'absolute', top: gridTop, left: gridLeft,
                    width: totalW, height: gridRowH * 3,
                    border: '1px solid black',
                  }}>
                    {/* Column dividers (full height) */}
                    {colPositions.slice(1).map((x, i) => (
                      <div key={`col-${i}`} style={{
                        position: 'absolute', left: x, top: 0,
                        width: 1, height: gridRowH * 3,
                        background: 'black',
                      }} />
                    ))}

                    {/* Row dividers */}
                    <div style={{ position: 'absolute', left: 0, top: gridRowH, width: totalW, height: 1, background: 'black' }} />
                    {/* Third row divider (shorter — from col 1 to col 11) */}
                    <div style={{ position: 'absolute', left: colPositions[1] - 10, top: gridRowH * 2, width: colPositions[12] - colPositions[1] - 35, height: 1, background: 'black' }} />

                    {/* Header row labels */}
                    {GRID_HEADERS.map((h, i) => {
                      if (!h) return null
                      return (
                        <div key={`h-${i}`} style={{
                          position: 'absolute',
                          left: colPositions[i],
                          top: 0,
                          width: GRID_COL_WIDTHS[i],
                          height: gridRowH,
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          fontSize: 9,
                          fontWeight: 'bold',
                        }}>
                          {h}
                        </div>
                      )
                    })}

                    {/* Row 2: "For Action" label + checkmarks */}
                    <div style={{
                      position: 'absolute', left: 5, top: gridRowH,
                      height: gridRowH, display: 'flex', alignItems: 'center',
                      fontSize: 10,
                    }}>
                      For Action
                    </div>

                    {/* Row 3: "Copy to" label + checkmarks */}
                    <div style={{
                      position: 'absolute', left: 5, top: gridRowH * 2,
                      height: gridRowH, display: 'flex', alignItems: 'center',
                      fontSize: 10,
                    }}>
                      Copy to
                    </div>

                    {/* Arabic "صورة إلى" in last column, row 2 */}
                    <div style={{
                      position: 'absolute',
                      left: colPositions[12],
                      top: gridRowH,
                      width: GRID_COL_WIDTHS[12],
                      height: gridRowH,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontSize: 11,
                      fontWeight: 700,
                      fontFamily: "'Dialog', 'Traditional Arabic', serif",
                      direction: 'rtl',
                    }}>
                      صورة إلى
                    </div>

                    {/* Tick marks for For Action (row 2) and Copy to (row 3) */}
                    {Array.from({ length: 11 }, (_, i) => {
                      const colIdx = i + 1
                      const dataIdx = i
                      const forActionChecked = fd[`forAction_${dataIdx}`]
                      const sendCopyChecked = fd[`sendCopy_${dataIdx}`]
                      return (
                        <div key={`ticks-${i}`}>
                          {forActionChecked && (
                            <div style={{
                              position: 'absolute',
                              left: colPositions[colIdx],
                              top: gridRowH,
                              width: GRID_COL_WIDTHS[colIdx],
                              height: gridRowH,
                              display: 'flex', alignItems: 'center', justifyContent: 'center',
                              fontSize: 12, fontWeight: 'bold',
                              fontFamily: "'Dialog', serif",
                            }}>✓</div>
                          )}
                          {sendCopyChecked && (
                            <div style={{
                              position: 'absolute',
                              left: colPositions[colIdx],
                              top: gridRowH * 2,
                              width: GRID_COL_WIDTHS[colIdx],
                              height: gridRowH,
                              display: 'flex', alignItems: 'center', justifyContent: 'center',
                              fontSize: 12, fontWeight: 'bold',
                              fontFamily: "'Dialog', serif",
                            }}>✓</div>
                          )}
                        </div>
                      )
                    })}
                  </div>
                )
              })()}

              {/* ── 6. RESPONSE SECTION ── */}
              {(() => {
                const responseTop = 325 + 22 * 3 + 10 // gridTop + 3 rows + gap
                const lineSpace = 25
                const startLineY = 15
                const numLines = 10
                const responseText = fd.response || ''

                return (
                  <div style={{
                    position: 'absolute', top: responseTop, left: 40, width: 515,
                  }}>
                    {/* Label */}
                    <span style={{ fontSize: 10, position: 'absolute', left: 5, top: 1 }}>Response :</span>
                    <div style={{
                      position: 'absolute', right: 30, top: 1,
                      fontSize: 11, fontWeight: 700,
                      fontFamily: "'Dialog', 'Traditional Arabic', serif",
                      direction: 'rtl',
                    }}>
                      الرد :
                    </div>

                    {/* Response lines */}
                    {Array.from({ length: numLines }, (_, k) => {
                      const ly = startLineY + k * lineSpace
                      const lineLeft = k === 0 ? 80 : 0
                      return (
                        <div key={`line-${k}`} style={{
                          position: 'absolute',
                          left: lineLeft,
                          top: ly,
                          right: 0,
                          borderBottom: '1px solid black',
                        }} />
                      )
                    })}

                    {/* Response text — sits between lines like handwriting on lined paper */}
                    {responseText && (
                      <div style={{
                        position: 'absolute',
                        left: 0,
                        top: 21,
                        right: 0,
                        fontSize: 14,
                        fontStyle: 'italic',
                        lineHeight: '25px',
                        overflow: 'hidden',
                        maxHeight: numLines * lineSpace,
                        wordBreak: 'break-word',
                        color: 'black',
                        textIndent: 145,
                        paddingLeft: 5,
                        paddingRight: 5,
                      }}>
                        {responseText}
                      </div>
                    )}
                  </div>
                )
              })()}
            </div>
          </div>
        )
      })}
    </div>
  )
}
